# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConjurCli < Formula
  desc "CyberArk Conjur command line interface"
  homepage "https://conjur.org"
  version "8.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/conjur-cli-go/releases/download/v8.0.5/conjur-cli-go_8.0.5_darwin_amd64.tar.gz"
      sha256 "57be51b591b19a8a5953c6d1640d8cfa95bc62928cbc92063884484fd0c99784"

      def install
        bin.install "conjur"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cyberark/conjur-cli-go/releases/download/v8.0.5/conjur-cli-go_8.0.5_darwin_arm64.tar.gz"
      sha256 "87096e1eb1dbaaa8c31dd552796bdf02fd3c375d3ba0d6d6de9fe9a4698e897d"

      def install
        bin.install "conjur"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cyberark/conjur-cli-go/releases/download/v8.0.5/conjur-cli-go_8.0.5_linux_arm64.tar.gz"
      sha256 "56800e4427b6ebd1924c3981d28ff488728874016fc2c916b386e2d235bf54bb"

      def install
        bin.install "conjur"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/conjur-cli-go/releases/download/v8.0.5/conjur-cli-go_8.0.5_linux_amd64.tar.gz"
      sha256 "ef3a1267954e299ae897cd68f7799cc1df3a535963716dbc0dc4aa8cb565199a"

      def install
        bin.install "conjur"
      end
    end
  end

  test do
    system "#{bin}/conjur", "--version"
  end
end
