# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConjurCli < Formula
  desc "CyberArk Conjur command line interface"
  homepage "https://conjur.org"
  version "8.0.10-356"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cyberark/conjur-cli-go/releases/download/v8.0.10/conjur-cli-go_8.0.10_darwin_arm64.tar.gz"
      sha256 "5f897d3eb407db005693211e3216e632170c6ff3555f85e82746fc93127ba521"

      def install
        bin.install "conjur"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/conjur-cli-go/releases/download/v8.0.10/conjur-cli-go_8.0.10_darwin_amd64.tar.gz"
      sha256 "3bdb08304c054b7d38afcc775853fad86980f7b4fc7cc0b51a6e0f57181958ed"

      def install
        bin.install "conjur"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/conjur-cli-go/releases/download/v8.0.10/conjur-cli-go_8.0.10_linux_amd64.tar.gz"
      sha256 "9dbb65fb57acf39f6a1bf8135e6f613d8605482ef3c0ba6d97f3152a8e3a2fb0"

      def install
        bin.install "conjur"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cyberark/conjur-cli-go/releases/download/v8.0.10/conjur-cli-go_8.0.10_linux_arm64.tar.gz"
      sha256 "a11463300fd6108481858b66983b9576c446c792d211ce5f3bd100dfc26b7649"

      def install
        bin.install "conjur"
      end
    end
  end

  test do
    system "#{bin}/conjur", "--version"
  end
end
