# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SecretlessBroker < Formula
  desc "Secures your apps by making them Secretless"
  homepage "https://secretless.io"
  version "1.7.16"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cyberark/secretless-broker/releases/download/v1.7.16/secretless-broker_1.7.16_darwin_arm64.tar.gz"
      sha256 "e3dba30dbecab39aefdef8b23e6e8d68af34519b69247fe5c34b5deed98a652f"

      def install
        bin.install "secretless-broker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/secretless-broker/releases/download/v1.7.16/secretless-broker_1.7.16_darwin_amd64.tar.gz"
      sha256 "f8fee7d52e658b5fd936f566e2dde699824a4555a612e02e1c8427d2163f9b93"

      def install
        bin.install "secretless-broker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/secretless-broker/releases/download/v1.7.16/secretless-broker_1.7.16_linux_amd64.tar.gz"
      sha256 "98805e253f47f62a49663cbd8068fb2afe65549dd919891189f849a8fe641254"

      def install
        bin.install "secretless-broker"
      end
    end
  end

  test do
    system "#{bin}/secretless-broker", "-version"
  end
end
