# This file was generated by GoReleaser. DO NOT EDIT.
class SecretlessBroker < Formula
  desc "Secures your apps by making them Secretless"
  homepage "https://secretless.io"
  version "1.4.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cyberark/secretless-broker/releases/download/v1.4.2/secretless-broker_1.4.2_darwin_amd64.tar.gz"
    sha256 "42999230c817edb3def74c136b89a283b4817455656dde59250ad1c974e28152"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/secretless-broker/releases/download/v1.4.2/secretless-broker_1.4.2_linux_amd64.tar.gz"
      sha256 "b88df1ab07863cfde97161fb6024b6a8937b39f4e95d957cc6e50c79438f20d2"
    end
  end

  def install
    bin.install "secretless-broker"
  end

  test do
    system "#{bin}/secretless-broker", "-version"
  end
end
