# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Summon < Formula
  desc "CLI that provides on-demand secrets access for common DevOps tools."
  homepage "https://github.com/cyberark/summon"
  version "0.9.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cyberark/summon/releases/download/v0.9.2/summon-darwin-arm64.tar.gz"
      sha256 "b25dd43ef7bb637cf2011dbb7479c5c3e32f3eccc37ec278f3caecae57f77292"

      def install
        bin.install "summon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/summon/releases/download/v0.9.2/summon-darwin-amd64.tar.gz"
      sha256 "cb7aeda72dcf7c388690253b36a284b80b158e25b67ef40f41f374b105b9ec64"

      def install
        bin.install "summon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/summon/releases/download/v0.9.2/summon-linux-amd64.tar.gz"
      sha256 "e02aa29bfc6791756d29a475a7d9ceeec96298f41834395981974f15fa3ffd4c"

      def install
        bin.install "summon"
      end
    end
  end

  test do
    system "#{bin}/summon", "-v"
  end
end
