# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SummonConjur < Formula
  desc "Conjur provider for Summon"
  homepage "https://github.com/cyberark/summon-conjur"
  version "0.7.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/summon-conjur/releases/download/v0.7.1/summon-conjur-darwin-amd64.tar.gz"
      sha256 "04f5972275b0f3c647d13e4b288050c5f6e61d27cfc8e3dfb965e81f771d2ec1"

      def install
        target = lib/"summon"
        target.install "summon-conjur"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cyberark/summon-conjur/releases/download/v0.7.1/summon-conjur-darwin-arm64.tar.gz"
      sha256 "cc68edf30529379422998e8b118bb11c613aaedc54380945413290f3245874a5"

      def install
        target = lib/"summon"
        target.install "summon-conjur"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/summon-conjur/releases/download/v0.7.1/summon-conjur-linux-amd64.tar.gz"
      sha256 "4187364b7178d18a6f47c68d0c95eaeb308ce711f550890da39bf25d8184ce44"

      def install
        target = lib/"summon"
        target.install "summon-conjur"
      end
    end
  end

  test do
    system lib/"summon"/"summon-conjur", "-V"
  end
end
