# This file was generated by GoReleaser. DO NOT EDIT.
class Summon < Formula
  desc "CLI that provides on-demand secrets access for common DevOps tools."
  homepage "https://github.com/cyberark/summon"
  version "0.8.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/cyberark/summon/releases/download/v0.8.1/summon-darwin-amd64.tar.gz"
    sha256 "e194ca4747d7192ed92b3661be8dfe40e31c8e685599241415ea761e40ce2339"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/summon/releases/download/v0.8.1/summon-linux-amd64.tar.gz"
      sha256 "3dafb21abbc0236e57a6e5faa39a951a8287ef8c02210f427f06b101bb177909"
    end
  end

  def install
    bin.install "summon"
  end

  test do
    system "#{bin}/summon", "-v"
  end
end
