# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SummonAwsSecrets < Formula
  desc "AWS Secrets Manager provider for Summon"
  homepage "https://github.com/cyberark/summon-aws-secrets"
  version "0.4.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cyberark/summon-aws-secrets/releases/download/v0.4.2/summon-aws-secrets-darwin-arm64.tar.gz"
      sha256 "ba9b88bd78542ab8a5d7c73c1848ee32707fdc679e56d4143763f8b6e54920cf"

      def install
        target = lib/"summon"
        target.install "summon-aws-secrets"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/summon-aws-secrets/releases/download/v0.4.2/summon-aws-secrets-darwin-amd64.tar.gz"
      sha256 "3939c011a78b7dd4e07ad3f814dc7d6b10797aec6f8409e0b0b485f3cec19f08"

      def install
        target = lib/"summon"
        target.install "summon-aws-secrets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/summon-aws-secrets/releases/download/v0.4.2/summon-aws-secrets-linux-amd64.tar.gz"
      sha256 "f15bdb52610aa3e3fe291b05341093ad3c99d5e6607ac95b86cfd3cd57afd53a"

      def install
        target = lib/"summon"
        target.install "summon-aws-secrets"
      end
    end
  end

  test do
    system lib/"summon"/"summon-aws-secrets", "-v"
  end
end
