# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformProviderConjur < Formula
  desc "Terraform provider for CyberArk Conjur"
  homepage "https://github.com/cyberark/terraform-provider-conjur"
  version "0.6.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cyberark/terraform-provider-conjur/releases/download/v0.6.3/terraform-provider-conjur_0.6.3_darwin_arm64.zip"
      sha256 "20e1b8f43b12f50abf04526cb4c68068b61510ac2d84a74e7a315213483869a6"

      def install
        bin.install "terraform-provider-conjur_v0.6.3"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/terraform-provider-conjur/releases/download/v0.6.3/terraform-provider-conjur_0.6.3_darwin_amd64.zip"
      sha256 "18caee192acc43e953b0038fb031749ec747a03699db7e867bee50d6e543a9c1"

      def install
        bin.install "terraform-provider-conjur_v0.6.3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cyberark/terraform-provider-conjur/releases/download/v0.6.3/terraform-provider-conjur_0.6.3_linux_amd64.zip"
      sha256 "8284e405a779efd4ec7661987062c1500d5b934feee3624c80eea4664f48a0e1"

      def install
        bin.install "terraform-provider-conjur_v0.6.3"
      end
    end
  end

  depends_on "terraform"

  def caveats; <<~EOS
    After installation, you must symlink the provider into Terraform's plugins directory.
    Symlinking is necessary because Homebrew is sandboxed and cannot write to your home directory.

    # Make the plugins directory if not present
    mkdir -p ~/.terraform.d/plugins/

    # Remove any old unversioned plugins (if applicable)
    rm -f  ~/.terraform.d/plugins/terraform-provider-conjur

    # Symlink the provider to your home dir. If Homebrew is installing somewhere other than /usr/local/Cellar, update the path as well.
    ln -sf /usr/local/Cellar/terraform-provider-conjur/0.6.3/bin/terraform-provider-conjur_v0.6.3 ~/.terraform.d/plugins/terraform-provider-conjur_v0.6.3
  EOS
  end

  test do
    # Running bin directly gives error, exit code 1
    system "#{bin}/terraform-provider-conjur_v0.6.3", "-h"
  end
end
